import { assets } from "@/assets";
import { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title: "Elite Commerce",
  description: "Generated by create next app",
  icons: { icon: assets.topFeatureImg2.src },

};
const page = () => {
  return (
    <div>
      <h1>Features page</h1>
    </div>
  );
};

export default page;
